project_id = "lbyoniuealghclfuahko"

[functions.send-signature-email]
verify_jwt = false

[functions.get-document-for-signing]
verify_jwt = false

[functions.sign-document]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.create-free-account]
verify_jwt = false

[functions.send-member-invitation]
verify_jwt = true

[functions.bry-get-token]
verify_jwt = false

[functions.bry-create-envelope]
verify_jwt = false

[functions.bry-webhook]
verify_jwt = false

[functions.bry-download-signed]
verify_jwt = false

[functions.bry-register-webhook]
verify_jwt = false

[functions.bry-sync-status]
verify_jwt = false

[functions.bry-download-report]
verify_jwt = false

[functions.bry-get-validation-url]
verify_jwt = false

[functions.apply-simple-signature]
verify_jwt = false

[functions.get-document-validation]
verify_jwt = false

[functions.bry-ar-auth]
verify_jwt = false

[functions.bry-ar-request-certificate]
verify_jwt = false

[functions.bry-ar-attach-document]
verify_jwt = false

[functions.bry-ar-check-psbio]
verify_jwt = false

[functions.bry-ar-list-requests]
verify_jwt = false

[functions.bry-ar-webhook]
verify_jwt = false

[functions.bry-ar-download-certificate]
verify_jwt = false

[functions.bry-ar-list-documents]
verify_jwt = false

[functions.bry-ar-get-document]
verify_jwt = false

[functions.bry-ar-delete-request]
verify_jwt = false

[functions.bry-ar-delete-document]
verify_jwt = false

[functions.bry-ar-get-request]
verify_jwt = false

[functions.bry-ar-download-ownership-term]
verify_jwt = false

[functions.generate-signature-report]
verify_jwt = false

[functions.send-document-completed-email]
verify_jwt = false

[functions.download-complete-document]
verify_jwt = false
