project_id = "lbyoniuealghclfuahko"

[functions.create-ticket]
verify_jwt = false

[functions.send-signature-email]
verify_jwt = false

[functions.get-document-for-signing]
verify_jwt = false

[functions.sign-document]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.create-free-account]
verify_jwt = false

[functions.send-member-invitation]
verify_jwt = true

[functions.bry-get-token]
verify_jwt = false

[functions.bry-create-envelope]
verify_jwt = false

[functions.bry-webhook]
verify_jwt = false

[functions.bry-download-signed]
verify_jwt = false

[functions.bry-register-webhook]
verify_jwt = false

[functions.bry-sync-status]
verify_jwt = false

[functions.bry-download-report]
verify_jwt = false

[functions.bry-get-validation-url]
verify_jwt = false

[functions.apply-simple-signature]
verify_jwt = false

[functions.get-document-validation]
verify_jwt = false

[functions.generate-signature-report]
verify_jwt = false

[functions.send-document-completed-email]
verify_jwt = false

[functions.download-complete-document]
verify_jwt = false

[functions.bry-prescription-metadata]
verify_jwt = false

[functions.send-prescription-to-patient]
verify_jwt = false

[functions.sign-with-local-certificate]
verify_jwt = false

[functions.bry-sync-cron]
verify_jwt = false

[functions.send-document-cancelled]
verify_jwt = false

[functions.set-member-password]
verify_jwt = false

[functions.delete-member]
verify_jwt = true

[functions.send-member-webhook]
verify_jwt = false

[functions.get-users-list]
verify_jwt = false

[functions.send-ticket-message]
verify_jwt = true

[functions.receive-ticket-response]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.mark-messages-read]
verify_jwt = true

[functions.sync-stripe-subscription]
verify_jwt = false
