project_id = "lbyoniuealghclfuahko"

[functions.send-signature-email]
verify_jwt = false

[functions.get-document-for-signing]
verify_jwt = false

[functions.sign-document]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false