project_id = "lbyoniuealghclfuahko"

[functions.send-signature-email]
verify_jwt = false

[functions.get-document-for-signing]
verify_jwt = false

[functions.sign-document]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.create-free-account]
verify_jwt = false

[functions.send-member-invitation]
verify_jwt = true

[functions.bry-get-token]
verify_jwt = false

[functions.bry-create-envelope]
verify_jwt = false

[functions.bry-webhook]
verify_jwt = false

[functions.bry-download-signed]
verify_jwt = false
